/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'lemiorhan' at '11/4/16 2:13 PM' with Gradle 2.13
 *
 * @author lemiorhan, @date 11/4/16 2:13 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
