import org.junit.Test;

import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'lemiorhan' at '11/4/16 2:13 PM' with Gradle 2.13
 *
 * @author lemiorhan, @date 11/4/16 2:13 PM
 */
public class LibraryTest {

    @Test
    public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());

        int i = new Library() + new Library();
    }
}
